[package]
name = "raytracer"
version = "0.3.0"
authors = ["LimelioN <memorial.limelion@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "^0.17.0"
image = "^0.23.0"
pbr = "^1.0.2"
rand = "^0.7.3"
